### PR TITLE
Added: third colortheme "graygray"

### PR DESCRIPTION
**Pull request by hoodie**
hey, I haven't looked in 13months, is such as pure-gray colortheme already part of your distro?

### CODE REVIEW

**Comment by derric** [comment]
Hey. I checked out your suggestion. As already mentioned, this competes the package option `colorize=bw`. The biggest differences are gray chapter numbers, section titles, and figure labels.
What I do not like so much is that by setting your gray-gray theme and my bw-option the same time, your gray-theme will be overwritten and transferred into another gray-theme.

Correct me if I am wrong, but your main motivation is probably to avoid the use of dark black for the elements mentioned above. Because I am kinda with you, I think that your suggestion should not result in another gray-theme, but in an improvement of the bw-option.

Therefore, I opened a new issue for that (#53).

**Comment by hoodie** [comment]
:smile: I think you shouldn't be up this late if you wanna go to work tomorrow.
And I like the idea :+1:

**Comment by derric** [comment]
Great. See you 😉

**Comment by derric** [comment]
Closed in favor of #53

**Pull request closed without merging**
